### ISSUE TITLE
Window doesn't appear under Wayland

### ISSUE THREAD

**Issue by markstos** [t-8ch/pinentry-bemenu#10]
I'm trying to use this with `dmenu-lass`, which works with other pinentry programs. With the others, a window appears and asks for my password. 

But with this, no window appears under Wayland. A few seconds later, a message is printed to the terminal "failed to enter correct password":

```
dmenu-lpass -u=mark@example.com --pinentry=/usr/bin/pinentry-bemenu
```

Is there more configuration that needs to be done? I don't use Bemenu for anything else, I use Fuzzel.

**Comment by t-8ch** [comment]
Do you have the wayland backend for bemenu installed?

Is a window shown when you execute `echo CONFIRM | pinentry-bemenu`?

**Comment by markstos** [comment]
I thought I selected it when installing the AUR package for Arch Linux, but I've since returned to using `pinentry-qt` which works for me, so I'll close this.
