### ISSUE TITLE
Show on active display

### ISSUE THREAD

**Issue by kedodrill** [t-8ch/pinentry-bemenu#13]
Hi there, I've really been enjoying using this as a pinentry replacement. I currently have a little script I use that runs bemenu to show a list of passwords which shows up on the active display (I have two monitors). Currently, pinentry-bemenu shows up only on my second monitor. Could this be changed easily so it shows up on the active display, like bemenu does it? Totally understand if you're not wanting to do this. Just figured it might be a good addition. :)

Possibly related: https://github.com/Cloudef/bemenu/issues/102

**Comment by ammgws** [comment]
Doesn't `--monitor -1` do that for you? That should show it on the focused monitor according to https://github.com/Cloudef/bemenu/pull/174/files, and pinentry-bemenu passes that alogn to bemenu so it should work

**Comment by t-8ch** [comment]
@kedodrill As @ammgws said the same  options as for plain bemenu should work.

One exception are the symbolical aliases "focused" and "all". For those you need the numerical values -1 and -2

**Comment by kedodrill** [comment]
Hmm, where would I put that argument? I'm on void linux and I'm using `xbps-alternatives` to symlink pinentry-bemenu as a replacement for pinentry. I tried putting `pinentry-program /usr/bin/pinentry-bemenu --monitor -1` in `gpg-agent.conf`, but I'm guessing that broke it because it no longer shows up.

**Comment by t-8ch** [comment]
@kedodrill Try to create a wrapper script that passes the configuration and use that in `gpg-agent.conf`

**Comment by t-8ch** [comment]
@kedodrill Did it work?

**Comment by kedodrill** [comment]
@t-8ch sorry for the delayed response! I did try a wrapper script but I couldn't get it to work. I'm guessing that void is doing something different here...switching back to the regular pinentry program using xbps-alternatives and then doing as you suggested above resulted in no program loading at all, with a "No pinentry" error. Any ideas?

**Comment by t-8ch** [comment]
But you did get `pinentry-bemenu` running without settings, correct? By setting it in `gpg-agent.conf`?
Can you create this script as `~/pinentry-test` and test if it works when running it manually and when adding it to `gpg-agent.conf`?:
```sh
#!/bin/sh
exec pinentry-bemenu
```
(Don't forget to make it executable.)

**Comment by kedodrill** [comment]
@t-8ch Got it working! I did what you said and then just added the `-m -1` that the first comment suggested. not sure why I couldn't get it working before, I swear I had it set up just like that...anyways thank you!

**Comment by t-8ch** [comment]
Nice to hear!
