### ISSUE TITLE
How to change the prompt?

### ISSUE THREAD

**Issue by ephemer4l** [t-8ch/pinentry-bemenu#14]
dmenu can be modified to an extent with the file `~/.gnupg/pinentry-dmenu.conf`. Are there any plans to support this with pinentry-bemenu? I'm trying to have an empty prompt or at least a shorter one because I can't see myself type anything as everything is condensed into the same line. Is there perhaps something I can pass to BEMENU_OPTS to prevent this?

**Comment by t-8ch** [comment]
> dmenu can be modified to an extent with the file ~/.gnupg/pinentry-dmenu.conf. Are there any plans to support this with pinentry-bemenu?

Not really.

> I'm trying to have an empty prompt or at least a shorter one because I can't see myself type anything as everything is condensed into the same line. Is there perhaps something I can pass to BEMENU_OPTS to prevent this?

The prompts are all supplied by the caller of pinentry-bemenu (ssh, gpg-agent, etc). So we can not really shorten them here.

As a fix it should be possible to render the prompts in multiple lines. This feature however would first have to be implemented in vanilla bemenu before we can use it here.

**Comment by juanmeleiro** [comment]
There is a feature request for this on Cloudef/bemenu#227.
