### ISSUE TITLE
SETTITLE Assuan protocol command not supported

### ISSUE THREAD

**Issue by timblaktu** [t-8ch/pinentry-bemenu#17]
I like the idea of using this ultra-lightweight widget as my "gui" pinentry in hyprland sessions, but when trying to use it with `rbw` as its pinentry program, I stumbled on its lack of support for the SETTITLE command:

```
[1]tim@thinky:~/auth > /usr/bin/pinentry-bemenu --center --monitor focused --line-height 64 --fn "Hack Nerd Font Mono [64]"
OK pinentry-bemenu 0.12.0
SETTITLE rbw
ERR 536871187 Unknown IPC command <User defined source 1>
```

Should be an easy fix. I can see [here](https://github.com/t-8ch/pinentry-bemenu/blob/703111104b3175cf223b1a422812a983165f367a/pinentry_bemenu.c#L78) and [in make_title](https://github.com/t-8ch/pinentry-bemenu/blob/703111104b3175cf223b1a422812a983165f367a/pinentry_bemenu.c#L51) that it's not aware of a separate title param, and just constructs one from the desc and prompt params.

**Comment by t-8ch** [comment]
The "title" here is the actual prompt shown to the user.
"SETTITLE" however sets the window title.
As with bemenu there is no actual window title we can't use it as-is.
Is the window title important for rbw?

Otherwise we could just ignore it.
