### ISSUE TITLE
error with rbw-menu

### ISSUE THREAD

**Issue by pfr-dev** [t-8ch/pinentry-bemenu#22]
I've initialised [rbw](https://github.com/doy/rbw) and configured [rbw-menu](https://github.com/rbuchberger/rbw-menu) to use `bemenu` & `pinentry-bemenu` but I get the following error

```
~ $ rbw-menu password | wl-copy
rbw unlock: failed to read password from pinentry: pinentry error: Unknown IPC command <User defined source 1>
```
The command inside `rbw-menu` is:
```
rbw list | bemenu "$query"
```

Strangely however, the `pinentry-bemenu` prompt does appear on the screen but the error appears at the same time leaving the prompt redundant. 

I'm on Alpine Linux Edge  wl-roots

**Comment by t-8ch** [comment]
Which version of `pinentry-bemenu` are you using?
It could be a duplicate of #17 which would be fixed by version 0.13

**Comment by pfr-dev** [comment]
Ahh thanks. Yeah, I'm using Version 0.12 which is what is currently what's available in the Alpine edge/testing repo.  I tried to build using `meson` but I'm getting a weird error

```
meson.build:1:0: ERROR: Compiler cc cannot compile programs.
```
This is a seperate issue which I'll hopefully figure out soon..

Are you able to reach out to the Jakub (the maintainer of the Alpine package) and request an update? Or I'm happy to, if you know their github handle?

**Comment by t-8ch** [comment]
I just flagged it here:
https://pkgs.alpinelinux.org/package/edge/testing/x86_64/pinentry-bemenu

**Comment by pfr-dev** [comment]
Thanks, and sorry, I'm new to Alpine an didn't know I could flag out of date packages. 

Looks like I fixed my C compiler issue anyway so might be able to build from git after all.

**Comment by pfr-dev** [comment]
Hmmmm dont suppose you can help me here...?

```
[dave] ~/Downloads/pinentry-bemenu % meson setup build
The Meson build system
Version: 1.3.2
Source dir: /home/dave/Downloads/pinentry-bemenu
Build dir: /home/dave/Downloads/pinentry-bemenu/build
Build type: native build
Project name: pinentry-bemenu
Project version: 0.13.1
C compiler for the host machine: cc (gcc 13.2.1 "cc (Alpine 13.2.1_git20240309) 13.2.1 20240309")
C linker for the host machine: cc ld.bfd 2.42
Host machine cpu family: x86_64
Host machine cpu: x86_64
Found pkg-config: YES (/usr/bin/pkg-config) 2.1.1
Found CMake: /usr/bin/cmake (3.28.3)
Run-time dependency bemenu found: NO (tried pkgconfig and cmake)

meson.build:15:9: ERROR: Dependency "bemenu" not found, tried pkgconfig and cmake

A full log can be found at /home/dave/Downloads/pinentry-bemenu/build/meson-logs/meson-log.txt
[dave] ~/Downloads/pinentry-bemenu % which bemenu
/usr/bin/bemenu
```

**Comment by t-8ch** [comment]
Try installing bemenu-dev

**Comment by pfr-dev** [comment]
Thanks, got it working :)
