### ISSUE TITLE
Pinentry for GPG doesn't work anymore.

### ISSUE THREAD

**Issue by oliverwiegers** [t-8ch/pinentry-bemenu#4]
I can confirm that the issue was fixed in [8947943](https://github.com/t-8ch/pinentry-bemenu/commit/89479431d405be61a252b3a3436e26bbba1475a5). But the issue was reintroduced in [dc74bc5](https://github.com/t-8ch/pinentry-bemenu/commit/dc74bc5fa82f610a65c2e12bab8bc6c707572732).
So current HEAD is not working for GPG keys anymore.

_Originally posted by @oliverwiegers in https://github.com/t-8ch/pinentry-bemenu/issues/1#issuecomment-829321724_

I don't know what the issue is. 

From the command line it looks like this:

```
❯ gpg --decrypt <path_to_file.gpg>
gpg: encrypted with 4096-bit RSA key, ID NOPEID, created 2019-09-13
      "Nope Nope (NOPEDOMAIN) <nope@nope>"
gpg: public key decryption failed: No pinentry
gpg: decryption failed: No secret key
```

**Comment by t-8ch** [comment]
This works for me. Can you run with `--debug` and provide the logs?
(Latest master has a small bugfix that may have a very small change of fixing this, too)

**Comment by oliverwiegers** [comment]
Yeah well... now it works for me to. I have no idea why. Sorry for bothering you.

**Comment by t-8ch** [comment]
Okay, no worries :-)
